//! The reader against documents nobody here wrote.
//!
//! The corpus in this repository is real Word output, but it is thin and it is
//! *ours* — generated by a script we wrote, exercising the features we thought
//! to ask for. Microsoft ships a folder of finished templates with Office, and
//! they are the opposite: written by Word's own designers, full of content
//! controls, glossary parts, floating art, themed tables and building blocks
//! that nothing here would have thought to generate.
//!
//! This is the same move as `ss-xls`'s check against `SOLVSAMP.XLS`. Fixtures
//! catch regressions; only a document written by the real application catches a
//! misunderstanding — `LEARNINGS.md` §5.
//!
//! The tests skip, loudly, when Office is not installed. Nothing is copied into
//! the repository: the files are read where they are, and no document belonging
//! to the user is touched.

use std::path::{Path, PathBuf};

use wp_model::doc::{Block, Inline, Piece};

/// Where Office keeps the templates it ships with. Several layouts exist across
/// versions and locales, so all of them are tried.
fn template_dirs() -> Vec<PathBuf> {
    let roots = [
        r"C:\Program Files\Microsoft Office\root",
        r"C:\Program Files (x86)\Microsoft Office\root",
        r"C:\Program Files\Microsoft Office",
    ];
    let leaves = [
        r"Templates\1033",
        r"Office16\1033\QuickStyles",
        r"Document Parts\1033\16",
    ];
    let mut found = Vec::new();
    for root in roots {
        for leaf in leaves {
            let path = Path::new(root).join(leaf);
            if path.is_dir() {
                found.push(path);
            }
        }
    }
    found
}

fn templates() -> Vec<PathBuf> {
    let mut files = Vec::new();
    for dir in template_dirs() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let is_word = path
                .extension()
                .and_then(|e| e.to_str())
                .is_some_and(|e| e.eq_ignore_ascii_case("dotx") || e.eq_ignore_ascii_case("docx"));
            if is_word {
                files.push(path);
            }
        }
    }
    files.sort();
    files
}

/// Prints the reason and returns true when there is nothing to test against.
fn absent() -> bool {
    if templates().is_empty() {
        eprintln!(
            "skipped: no Office templates found. These tests read \
             C:\\Program Files\\Microsoft Office\\root\\Templates and skip when \
             Office is not installed."
        );
        return true;
    }
    false
}

/// What one document turned out to contain, for the aggregate assertions.
#[derive(Default, Debug)]
struct Seen {
    paragraphs: usize,
    tables: usize,
    controls: usize,
    drawings: usize,
    hyperlinks: usize,
    fields: usize,
    headers: usize,
    numbered: usize,
    rendered_breaks: usize,
    characters: usize,
}

fn survey(document: &wp_model::Document) -> Seen {
    let mut seen = Seen {
        headers: document.headers.len(),
        ..Seen::default()
    };
    fn walk(blocks: &[Block], seen: &mut Seen) {
        for block in blocks {
            match block {
                Block::Paragraph(_) => {}
                Block::Table(table) => {
                    seen.tables += 1;
                    for row in &table.rows {
                        for cell in &row.cells {
                            walk(&cell.content, seen);
                        }
                    }
                }
                Block::Structured(sdt) => {
                    seen.controls += 1;
                    walk(&sdt.content, seen);
                }
                _ => {}
            }
        }
    }
    walk(&document.body, &mut seen);

    for paragraph in document.paragraphs() {
        seen.paragraphs += 1;
        seen.characters += paragraph.text().chars().count();
        seen.rendered_breaks += paragraph.rendered_page_breaks();
        if paragraph.props.numbering.is_some_and(|n| n.is_numbered()) {
            seen.numbered += 1;
        }
        for inline in &paragraph.content {
            match inline {
                Inline::Hyperlink(_) => seen.hyperlinks += 1,
                Inline::Structured(_) => seen.controls += 1,
                Inline::SimpleField { .. } => seen.fields += 1,
                _ => {}
            }
        }
        for piece in paragraph.runs().iter().flat_map(|run| &run.content) {
            match piece {
                Piece::Drawing(_) => seen.drawings += 1,
                Piece::FieldStart { .. } => seen.fields += 1,
                _ => {}
            }
        }
    }
    seen
}

#[test]
fn every_template_office_ships_opens() {
    if absent() {
        return;
    }
    let mut opened = 0;
    for path in templates() {
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        let (document, package) = wp_docx::open(&path).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert!(
            package.parts().count() > 3,
            "{name}: a real template has more than three parts"
        );
        assert!(
            document.section.page.width.0 > 0,
            "{name}: no page size was read"
        );
        assert!(
            !document.body.is_empty(),
            "{name}: opened with an empty body"
        );
        // Every style a reference names must resolve. This is the check that
        // would catch the two halves of the style table drifting apart.
        for paragraph in document.paragraphs() {
            if let Some(id) = paragraph.props.style {
                assert!(
                    document.styles.get(id).is_some(),
                    "{name}: a paragraph names a style that is not in the table"
                );
            }
            for run in paragraph.runs() {
                if let Some(id) = run.props.style {
                    assert!(
                        document.styles.get(id).is_some(),
                        "{name}: a run names a style that is not in the table"
                    );
                }
            }
        }
        opened += 1;
    }
    eprintln!("{opened} Office templates opened");
    assert!(opened >= 5, "found only {opened} templates");
}

#[test]
fn between_them_the_templates_exercise_what_the_corpus_does_not() {
    if absent() {
        return;
    }
    let mut total = Seen::default();
    let mut deepest = (0usize, String::new());
    for path in templates() {
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        let Ok((document, _)) = wp_docx::open(&path) else {
            continue;
        };
        let seen = survey(&document);
        if seen.paragraphs > deepest.0 {
            deepest = (seen.paragraphs, name);
        }
        total.paragraphs += seen.paragraphs;
        total.tables += seen.tables;
        total.controls += seen.controls;
        total.drawings += seen.drawings;
        total.hyperlinks += seen.hyperlinks;
        total.fields += seen.fields;
        total.headers += seen.headers;
        total.numbered += seen.numbered;
        total.rendered_breaks += seen.rendered_breaks;
        total.characters += seen.characters;
    }
    eprintln!("{total:?}");
    eprintln!("most paragraphs: {} in {}", deepest.0, deepest.1);

    assert!(total.paragraphs > 200, "{total:?}");
    assert!(total.characters > 5_000, "the text came through: {total:?}");
    assert!(total.tables > 0, "{total:?}");
    assert!(
        total.controls > 50,
        "Word's templates are made of content controls: {total:?}"
    );
    assert!(total.drawings > 0, "{total:?}");
    assert!(total.headers > 0, "{total:?}");
    assert!(
        total.numbered > 0,
        "somewhere in a folder of letters and reports there is a list: {total:?}"
    );
}

#[test]
fn a_style_chain_in_a_real_template_resolves_to_a_real_size() {
    if absent() {
        return;
    }
    // The four-layer resolution, run against styles a designer wrote rather than
    // ones we made up. A heading whose size resolves to nothing means a layer
    // was skipped, and the document would render in the fallback font — which
    // looks like a rendering bug rather than a resolution one.
    let mut checked = 0;
    for path in templates() {
        let Ok((document, _)) = wp_docx::open(&path) else {
            continue;
        };
        for paragraph in document.paragraphs() {
            let numbering = paragraph
                .props
                .numbering
                .and_then(|reference| document.numbering.layers(reference));
            let layers = document
                .styles
                .resolve_paragraph(&paragraph.props, numbering.as_ref());
            for run in paragraph.runs() {
                let resolved = document.styles.resolve_run(&layers, &run.props);
                // Not `is_some`: a document need not state a size anywhere at
                // all, and several of these do not. What must hold is that the
                // size a renderer would use is a real one, whether it came from
                // the file or from Word's own 10pt fallback.
                let points = resolved.font_size().points();
                assert!(
                    (1.0..=1638.0).contains(&points),
                    "{}: a run resolved to {points}pt",
                    path.display()
                );
                checked += 1;
            }
        }
    }
    assert!(checked > 100, "only {checked} runs were resolved");
    eprintln!("{checked} runs resolved through the full style chain");
}

#[test]
fn word_left_its_own_page_breaks_in_at_least_one_shipped_document() {
    if absent() {
        return;
    }
    // `<w:lastRenderedPageBreak>` is the only opinion about pagination a .docx
    // contains, and it is the nearest thing C19 has to an oracle. Our own corpus
    // has none — those documents were produced through COM and never displayed.
    // A document Word actually laid out is where one comes from.
    let mut with_breaks = Vec::new();
    for path in templates() {
        let Ok((document, _)) = wp_docx::open(&path) else {
            continue;
        };
        let breaks: usize = document
            .paragraphs()
            .iter()
            .map(|paragraph| paragraph.rendered_page_breaks())
            .sum();
        if breaks > 0 {
            with_breaks.push((
                path.file_name().unwrap().to_string_lossy().into_owned(),
                breaks,
            ));
        }
    }
    eprintln!("documents carrying Word's own page breaks: {with_breaks:?}");
    // Not asserted: whether any shipped template happens to carry one is
    // Microsoft's business, not a property of this reader. The list is printed
    // so C19 can pick its oracle from it, and so its absence is visible rather
    // than assumed.
}
