[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ooxml.workspace = true
ss-model.workspace = true
ss-xlsx.workspace = true
wp-model.workspace = true
wp-docx.workspace = true
wp-layout.workspace = true
ss-formula.workspace = true
