//! Shared application shell for Calx and Scriva.
//!
//! Window setup, config/state directory resolution, and the chrome both apps have
//! in common. The document surfaces themselves are *not* built from egui layout —
//! each app owns a custom widget that lays out and paints directly (see `DESIGN.md` §6).

#![forbid(unsafe_code)]

pub mod assist;
pub mod brand;
pub mod catalogue;
pub mod chart;
pub mod chooser;
pub mod dialog;
pub mod drive;
pub mod fonts;
pub mod headless;
pub mod keys;
pub mod menu;
pub mod paths;
pub mod recent;
pub mod scroll;
pub mod shell;
pub mod theme;

pub use eframe::{self, egui};
pub use fonts::Family;
pub use recent::Recent;
pub use shell::{run, DocumentApp};

/// Identity of a host application, used for window titles and config paths.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AppId {
    /// Lowercase, filesystem-safe name. Also the config directory name.
    pub slug: &'static str,
    /// Human-readable name shown in the window title.
    pub display: &'static str,
}

pub const CALX: AppId = AppId {
    slug: "calx",
    display: "Calx",
};
pub const SCRIVA: AppId = AppId {
    slug: "scriva",
    display: "Scriva",
};
/// The suite itself, for what one choice serves both applications: Assist's
/// helper, and what is downloaded for it.
pub const OFFICINA: AppId = AppId {
    slug: "officina",
    display: "Officina",
};

#[cfg(test)]
mod notices {
    use std::path::{Path, PathBuf};

    /// Every crate the suite ships is named in `THIRD-PARTY-NOTICES.yml`,
    /// with a licence.
    ///
    /// **A dependency that arrives without its licence is a release that
    /// cannot go out.** The file is generated by `cargo bundle-licenses`, and
    /// nothing runs that in the gate — it reads the whole registry — so what
    /// the gate can do is notice that a manifest names something the file has
    /// never heard of. The check is the direct dependencies of every crate in
    /// the tree, which is what a person adds when they add one.
    #[test]
    fn the_notices_name_every_crate_the_suite_ships() {
        let top = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let notices = std::fs::read_to_string(top.join("THIRD-PARTY-NOTICES.yml"))
            .expect("THIRD-PARTY-NOTICES.yml is at the top of the tree");
        let named: Vec<String> = notices
            .lines()
            .filter_map(|line| line.strip_prefix("- package_name: "))
            .map(|name| name.trim().replace('_', "-"))
            .collect();
        assert!(named.len() > 100, "the file is a real one: {}", named.len());

        let mut missing: Vec<String> = Vec::new();
        for manifest in manifests(&top) {
            let text = std::fs::read_to_string(&manifest).expect("a manifest");
            for crate_name in dependencies(&text) {
                // A crate of this workspace is not a third party.
                if workspace_members(&top).contains(&crate_name) {
                    continue;
                }
                if !named.contains(&crate_name) && !missing.contains(&crate_name) {
                    missing.push(crate_name);
                }
            }
        }
        assert!(
            missing.is_empty(),
            "crates the manifests name and the notices do not: {missing:?} — run \
             `cargo bundle-licenses --format yaml --output THIRD-PARTY-NOTICES.yml`"
        );
    }

    /// Every workspace member's manifest — the crates, and the tools beside
    /// them: `xtask` is a member too, and a dependency added there would
    /// otherwise never be looked at.
    fn manifests(top: &Path) -> Vec<PathBuf> {
        let mut found = Vec::new();
        for dir in [top.to_path_buf(), top.join("crates")] {
            let Ok(entries) = std::fs::read_dir(&dir) else {
                continue;
            };
            for entry in entries.flatten() {
                let manifest = entry.path().join("Cargo.toml");
                if manifest.exists() {
                    found.push(manifest);
                }
            }
        }
        assert!(
            found.iter().any(|at| at.ends_with("xtask/Cargo.toml")),
            "the tools are looked at as well as the crates"
        );
        found
    }

    /// The crates a manifest depends on when the suite is built: its
    /// `[dependencies]` and its target-specific ones, and not what only its
    /// own tests use.
    fn dependencies(manifest: &str) -> Vec<String> {
        let mut found = Vec::new();
        let mut shipped = false;
        for line in manifest.lines() {
            let line = line.trim();
            if line.starts_with('[') {
                shipped = line == "[dependencies]"
                    || (line.starts_with("[target.") && line.ends_with(".dependencies]"));
                continue;
            }
            if !shipped || line.starts_with('#') || line.is_empty() {
                continue;
            }
            if let Some((name, _)) = line.split_once('=') {
                // `ooxml.workspace = true` names the crate, not a key of it;
                // and a name written with underscores is the same crate as
                // one written with dashes.
                let name = name.trim().trim_matches('"');
                let name = name.split('.').next().unwrap_or(name);
                if !name.is_empty() {
                    found.push(name.replace('_', "-"));
                }
            }
        }
        found
    }

    fn workspace_members(top: &Path) -> Vec<String> {
        let manifest = std::fs::read_to_string(top.join("Cargo.toml")).expect("the workspace");
        manifest
            .lines()
            .filter_map(|line| line.split_once(" = { path = "))
            .map(|(name, _)| name.trim().to_owned())
            .collect()
    }
}
