//! `MAP.md`: where things are, for whoever has to find them — generated from
//! the repository itself, so it cannot drift from it.
//!
//! Half of an agent's tool calls in this repository used to be orientation:
//! which target holds a crate's tests, which file a dialog is in, where the
//! rule a measurement produced was written down. Every answer was already in
//! the tree — a crate's manifest, a module's first doc line, a comment that
//! says what Word measured — and scattered across a hundred files. This
//! gathers them into one page. It is rewritten by `cargo xtask map` and by
//! `cargo xtask check`, the way formatting is: a map one step behind the code
//! is worse than none, and nobody should have to remember to renew it.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::workspace_root;

pub fn write() -> Result<PathBuf, String> {
    let root = workspace_root();
    let mut text = render(&root)?;
    text.push_str(&menus(&root)?);
    let path = root.join("MAP.md");
    if std::fs::read_to_string(&path).ok().as_deref() != Some(text.as_str()) {
        std::fs::write(&path, &text).map_err(|e| format!("{}: {e}", path.display()))?;
    }
    Ok(path)
}

struct Krate {
    name: String,
    dir: String,
    what: String,
    bin: bool,
    lib: bool,
    tests: Vec<String>,
    files: Vec<(String, usize, String)>,
}

fn render(root: &Path) -> Result<String, String> {
    let mut crates = Vec::new();
    let mut dirs: Vec<PathBuf> = std::fs::read_dir(root.join("crates"))
        .map_err(|e| format!("crates/: {e}"))?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.join("Cargo.toml").exists())
        .collect();
    dirs.sort();
    for dir in dirs {
        crates.push(krate(root, &dir)?);
    }

    let mut out = String::new();
    out.push_str(
        "# Map\n\n\
         Generated by `cargo xtask map`, and again by every `cargo xtask check` — do not edit by hand. \
         Where each thing is, how to run its tests, and every comment that states what an application \
         was measured to do. The *why* of each is at the place it points to.\n\n\
         ## Crates\n\n\
         | crate | directory | tests | what |\n|---|---|---|---|\n",
    );
    for k in &crates {
        let mut how = Vec::new();
        if k.lib {
            how.push(format!("`-p {} --lib`", k.name));
        }
        if k.bin {
            how.push(format!("`-p {} --bin {}`", k.name, k.name));
        }
        for t in &k.tests {
            how.push(format!("`--test {t}`"));
        }
        let _ = writeln!(
            out,
            "| `{}` | `{}` | {} | {} |",
            k.name,
            k.dir,
            how.join(" "),
            k.what.replace('|', "\\|")
        );
    }

    out.push_str(
        "\n## Files\n\nEvery source file, its size, and the first sentence of its module doc.\n",
    );
    for k in &crates {
        let _ = writeln!(out, "\n### `{}`\n", k.name);
        for (file, lines, what) in &k.files {
            let _ = writeln!(out, "- `{file}` ({lines}) {}", what);
        }
    }

    out.push_str(
        "\n## Measured\n\n\
         Every comment that says an application was *measured* — the rules this code keeps because \
         Word, Excel or LibreOffice was asked, not because they were reasoned out. One line each, \
         cut at the sentence; the rest of the comment is at the place. A sentence counts when it says \
         \"measured\" and names what was asked, so a rule written without both is missing here: \
         write both, and it will be listed.\n",
    );
    for k in &crates {
        let mut facts = Vec::new();
        for (file, _, _) in &k.files {
            facts.extend(measured(&root.join(file), file));
        }
        if facts.is_empty() {
            continue;
        }
        let _ = writeln!(out, "\n### `{}`\n", k.name);
        for fact in facts {
            let _ = writeln!(out, "{fact}");
        }
    }
    Ok(out)
}

/// Every menu of both applications and the keys that reach each row, walked
/// by each application's own test through the in-process driver — so the
/// table is what the keyboard does, not what somebody wrote down.
fn menus(root: &Path) -> Result<String, String> {
    let dir = root.join("target").join("map");
    std::fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    let mut out = String::from(
        "\n## Menus\n\n\
         Every row of every menu, and the keys that choose it from the document — walked by \
         `no_two_rows_of_a_menu_share_a_letter` in each application, which also fails if two rows \
         of one menu share a letter. Rows without a letter are reached by the arrows or the pointer.\n",
    );
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".into());
    for (app, target) in [("scriva", "--lib"), ("calx", "--bin")] {
        let file = dir.join(format!("{app}-menus.md"));
        let _ = std::fs::remove_file(&file);
        // `--exact` wants the test's full path, which differs by where each
        // application keeps its tests.
        let path = match app {
            "scriva" => "app::tests::no_two_rows_of_a_menu_share_a_letter",
            _ => "tests::no_two_rows_of_a_menu_share_a_letter",
        };
        let mut args = vec!["test", "-q", "-p", app, target];
        if target == "--bin" {
            args.push(app);
        }
        args.extend([path, "--", "--exact"]);
        let status = std::process::Command::new(&cargo)
            .args(&args)
            .env("OFFICINA_MENUS_OUT", &file)
            .current_dir(root)
            .stdout(std::process::Stdio::null())
            .status()
            .map_err(|e| format!("cargo test for {app}'s menus: {e}"))?;
        let table = std::fs::read_to_string(&file).map_err(|_| {
            format!("{app}'s menu walk wrote nothing (the test exited with {status})")
        })?;
        let title = match app {
            "scriva" => "Scriva",
            _ => "Calx",
        };
        out.push_str(&format!("\n### {title}\n\n{table}"));
    }
    Ok(out)
}

fn krate(root: &Path, dir: &Path) -> Result<Krate, String> {
    let manifest = std::fs::read_to_string(dir.join("Cargo.toml"))
        .map_err(|e| format!("{}: {e}", dir.display()))?;
    let name = manifest
        .lines()
        .find_map(|l| {
            l.trim()
                .strip_prefix("name = ")?
                .trim()
                .strip_prefix('"')?
                .strip_suffix('"')
        })
        .unwrap_or("?")
        .to_owned();
    let src = dir.join("src");
    let lib = src.join("lib.rs").exists();
    let bin = src.join("main.rs").exists() || manifest.contains("[[bin]]");
    let head = if lib {
        src.join("lib.rs")
    } else {
        src.join("main.rs")
    };
    let what = first_sentence(&head);
    let mut tests: Vec<String> = std::fs::read_dir(dir.join("tests"))
        .map(|rd| {
            rd.flatten()
                .map(|e| e.path())
                .filter(|p| p.extension().is_some_and(|e| e == "rs"))
                .filter_map(|p| Some(p.file_stem()?.to_string_lossy().into_owned()))
                .collect()
        })
        .unwrap_or_default();
    tests.sort();
    let mut files = Vec::new();
    let mut paths = Vec::new();
    walk(&src, &mut paths);
    paths.sort();
    for path in paths {
        let rel = path
            .strip_prefix(root)
            .unwrap_or(&path)
            .to_string_lossy()
            .replace('\\', "/");
        let lines = std::fs::read_to_string(&path)
            .map(|t| t.lines().count())
            .unwrap_or(0);
        files.push((rel, lines, first_sentence(&path)));
    }
    Ok(Krate {
        name,
        dir: dir
            .strip_prefix(root)
            .unwrap_or(dir)
            .to_string_lossy()
            .replace('\\', "/"),
        what,
        bin,
        lib,
        tests,
        files,
    })
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in rd.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
}

/// The module doc's first sentence, or nothing.
fn first_sentence(path: &Path) -> String {
    let Ok(text) = std::fs::read_to_string(path) else {
        return String::new();
    };
    let mut doc = String::new();
    for line in text.lines() {
        let Some(rest) = line.trim_start().strip_prefix("//!") else {
            if doc.is_empty() && (line.trim().is_empty() || line.trim_start().starts_with("#!")) {
                continue;
            }
            break;
        };
        let rest = rest.trim();
        if rest.is_empty() {
            if doc.is_empty() {
                continue;
            }
            break;
        }
        if !doc.is_empty() {
            doc.push(' ');
        }
        doc.push_str(rest);
    }
    sentence(&doc)
}

/// Up to the first full stop that ends a sentence, and no longer than a line.
fn sentence(text: &str) -> String {
    let mut cut = text.len();
    let bytes = text.as_bytes();
    for (i, c) in text.char_indices() {
        if c == '.' && bytes.get(i + 1).is_none_or(|b| *b == b' ') {
            cut = i + 1;
            break;
        }
    }
    let mut s = text[..cut].trim().to_owned();
    if s.chars().count() > 220 {
        s = s.chars().take(217).collect::<String>() + "…";
    }
    s
}

/// The comments in `path` that say something was measured, as one line each.
fn measured(path: &Path, rel: &str) -> Vec<String> {
    let Ok(text) = std::fs::read_to_string(path) else {
        return Vec::new();
    };
    // Test files state what a test measures of the code, not of an
    // application, and would drown the rest.
    if rel.ends_with("/tests.rs") || rel.contains("/tests/") {
        return Vec::new();
    }
    let lines: Vec<&str> = text.lines().collect();
    let comment = |line: &str| -> Option<String> {
        let t = line.trim_start();
        let body = t
            .strip_prefix("///")
            .or_else(|| t.strip_prefix("//!"))
            .or_else(|| t.strip_prefix("//"))?;
        Some(body.trim().to_owned())
    };
    let mut out = Vec::new();
    let mut i = 0;
    while i < lines.len() {
        let Some(body) = comment(lines[i]) else {
            i += 1;
            continue;
        };
        let lower = body.to_lowercase();
        let Some(at) = lower.find("measured") else {
            i += 1;
            continue;
        };
        // The sentence the word is in: back to the start of the comment
        // block's sentence, on to its end.
        let mut start = i;
        while start > 0 {
            match comment(lines[start - 1]) {
                Some(prev) if !prev.is_empty() && !ends_sentence(&prev) => start -= 1,
                _ => break,
            }
        }
        let mut joined = String::new();
        let mut end = start;
        while end < lines.len() {
            let Some(body) = comment(lines[end]) else {
                break;
            };
            if body.is_empty() && end > i {
                break;
            }
            if !joined.is_empty() {
                joined.push(' ');
            }
            joined.push_str(&body);
            end += 1;
            if end > i && ends_sentence(&body) {
                break;
            }
        }
        let _ = at;
        // Of the joined text, the sentence that holds "measured".
        let lowered = joined.to_lowercase();
        let hit = lowered.find("measured").unwrap_or(0);
        let from = joined[..hit].rfind(". ").map(|p| p + 2).unwrap_or(0);
        let fact = sentence(&joined[from..]);
        // "Measured from A1" is geometry, not a measurement: what an
        // application was asked names the application, or the probe that
        // asked it.
        if names_an_oracle(&fact) {
            out.push(format!("- `{rel}:{}` {fact}", i + 1));
        }
        i = end.max(i + 1);
    }
    out
}

/// Whether a sentence names what was asked: an application, COM, a probe.
fn names_an_oracle(text: &str) -> bool {
    const ORACLES: [&str; 7] = [
        "Word",
        "Excel",
        "LibreOffice",
        "COM",
        "probe",
        "reference machine",
        "Office",
    ];
    ORACLES.iter().any(|name| {
        text.match_indices(name).any(|(at, _)| {
            let before = text[..at].chars().next_back();
            let after = text[at + name.len()..].chars().next();
            !before.is_some_and(char::is_alphanumeric) && !after.is_some_and(char::is_alphanumeric)
        })
    })
}

fn ends_sentence(text: &str) -> bool {
    let t = text.trim_end();
    t.ends_with('.') || t.ends_with(':') || t.ends_with('?')
}
