//! The built-in function table: BIFF stores a function as a number.
//!
//! Two token forms use it. `ptgFuncVar` carries its own argument count, so for
//! those the arity below is never consulted. `ptgFunc` does not — the count is
//! implied by *which* function it is, and a reader that guesses wrong pops the
//! wrong number of operands and silently produces a different formula.
//!
//! So [`VAR`] is used for anything whose fixed arity is not certain. A
//! `ptgFunc` naming one of those makes the whole formula undecompilable, and
//! the cell keeps its cached value instead — a visible gap rather than a
//! plausible wrong answer. In practice this costs nothing, because a function
//! with a variable argument count is always written as `ptgFuncVar`.

/// Not a fixed arity.
pub(crate) const VAR: u8 = 0xFF;

/// The function's name and, where it is fixed, how many arguments it takes.
pub(crate) fn lookup(index: u16) -> Option<(&'static str, u8)> {
    Some(match index {
        0 => ("COUNT", VAR),
        1 => ("IF", VAR),
        2 => ("ISNA", 1),
        3 => ("ISERROR", 1),
        4 => ("SUM", VAR),
        5 => ("AVERAGE", VAR),
        6 => ("MIN", VAR),
        7 => ("MAX", VAR),
        8 => ("ROW", VAR),
        9 => ("COLUMN", VAR),
        10 => ("NA", 0),
        11 => ("NPV", VAR),
        12 => ("STDEV", VAR),
        13 => ("DOLLAR", VAR),
        14 => ("FIXED", VAR),
        15 => ("SIN", 1),
        16 => ("COS", 1),
        17 => ("TAN", 1),
        18 => ("ATAN", 1),
        19 => ("PI", 0),
        20 => ("SQRT", 1),
        21 => ("EXP", 1),
        22 => ("LN", 1),
        23 => ("LOG10", 1),
        24 => ("ABS", 1),
        25 => ("INT", 1),
        26 => ("SIGN", 1),
        27 => ("ROUND", 2),
        28 => ("LOOKUP", VAR),
        29 => ("INDEX", VAR),
        30 => ("REPT", 2),
        31 => ("MID", 3),
        32 => ("LEN", 1),
        33 => ("VALUE", 1),
        34 => ("TRUE", 0),
        35 => ("FALSE", 0),
        36 => ("AND", VAR),
        37 => ("OR", VAR),
        38 => ("NOT", 1),
        39 => ("MOD", 2),
        40 => ("DCOUNT", 3),
        41 => ("DSUM", 3),
        42 => ("DAVERAGE", 3),
        43 => ("DMIN", 3),
        44 => ("DMAX", 3),
        45 => ("DSTDEV", 3),
        46 => ("VAR", VAR),
        47 => ("DVAR", 3),
        48 => ("TEXT", 2),
        49 => ("LINEST", VAR),
        50 => ("TREND", VAR),
        51 => ("LOGEST", VAR),
        52 => ("GROWTH", VAR),
        56 => ("PV", VAR),
        57 => ("FV", VAR),
        58 => ("NPER", VAR),
        59 => ("PMT", VAR),
        60 => ("RATE", VAR),
        61 => ("MIRR", 3),
        62 => ("IRR", VAR),
        63 => ("RAND", 0),
        64 => ("MATCH", VAR),
        65 => ("DATE", 3),
        66 => ("TIME", 3),
        67 => ("DAY", 1),
        68 => ("MONTH", 1),
        69 => ("YEAR", 1),
        70 => ("WEEKDAY", VAR),
        71 => ("HOUR", 1),
        72 => ("MINUTE", 1),
        73 => ("SECOND", 1),
        74 => ("NOW", 0),
        75 => ("AREAS", 1),
        76 => ("ROWS", 1),
        77 => ("COLUMNS", 1),
        78 => ("OFFSET", VAR),
        82 => ("SEARCH", VAR),
        83 => ("TRANSPOSE", 1),
        86 => ("TYPE", 1),
        97 => ("ATAN2", 2),
        98 => ("ASIN", 1),
        99 => ("ACOS", 1),
        100 => ("CHOOSE", VAR),
        101 => ("HLOOKUP", VAR),
        102 => ("VLOOKUP", VAR),
        105 => ("ISREF", 1),
        109 => ("LOG", VAR),
        111 => ("CHAR", 1),
        112 => ("LOWER", 1),
        113 => ("UPPER", 1),
        114 => ("PROPER", 1),
        115 => ("LEFT", VAR),
        116 => ("RIGHT", VAR),
        117 => ("EXACT", 2),
        118 => ("TRIM", 1),
        119 => ("REPLACE", 4),
        120 => ("SUBSTITUTE", VAR),
        121 => ("CODE", 1),
        124 => ("FIND", VAR),
        125 => ("CELL", VAR),
        126 => ("ISERR", 1),
        127 => ("ISTEXT", 1),
        128 => ("ISNUMBER", 1),
        129 => ("ISBLANK", 1),
        130 => ("T", 1),
        131 => ("N", 1),
        140 => ("DATEVALUE", 1),
        141 => ("TIMEVALUE", 1),
        142 => ("SLN", 3),
        143 => ("SYD", 4),
        144 => ("DDB", VAR),
        148 => ("INDIRECT", VAR),
        162 => ("CLEAN", 1),
        163 => ("MDETERM", 1),
        164 => ("MINVERSE", 1),
        165 => ("MMULT", 2),
        167 => ("IPMT", VAR),
        168 => ("PPMT", VAR),
        169 => ("COUNTA", VAR),
        183 => ("PRODUCT", VAR),
        184 => ("FACT", 1),
        189 => ("DPRODUCT", 3),
        190 => ("ISNONTEXT", 1),
        193 => ("STDEVP", VAR),
        194 => ("VARP", VAR),
        195 => ("DSTDEVP", 3),
        196 => ("DVARP", 3),
        197 => ("TRUNC", VAR),
        198 => ("ISLOGICAL", 1),
        199 => ("DCOUNTA", 3),
        204 => ("USDOLLAR", VAR),
        205 => ("FINDB", VAR),
        206 => ("SEARCHB", VAR),
        207 => ("REPLACEB", 4),
        208 => ("LEFTB", VAR),
        209 => ("RIGHTB", VAR),
        210 => ("MIDB", 3),
        211 => ("LENB", 1),
        212 => ("ROUNDUP", 2),
        213 => ("ROUNDDOWN", 2),
        214 => ("ASC", 1),
        215 => ("DBCS", 1),
        216 => ("RANK", VAR),
        219 => ("ADDRESS", VAR),
        220 => ("DAYS360", VAR),
        221 => ("TODAY", 0),
        222 => ("VDB", VAR),
        227 => ("MEDIAN", VAR),
        228 => ("SUMPRODUCT", VAR),
        229 => ("SINH", 1),
        230 => ("COSH", 1),
        231 => ("TANH", 1),
        232 => ("ASINH", 1),
        233 => ("ACOSH", 1),
        234 => ("ATANH", 1),
        235 => ("DGET", 3),
        244 => ("INFO", 1),
        247 => ("DB", VAR),
        252 => ("FREQUENCY", 2),
        261 => ("ERROR.TYPE", 1),
        269 => ("AVEDEV", VAR),
        270 => ("BETADIST", VAR),
        271 => ("GAMMALN", 1),
        272 => ("BETAINV", VAR),
        273 => ("BINOMDIST", 4),
        274 => ("CHIDIST", 2),
        275 => ("CHIINV", 2),
        276 => ("COMBIN", 2),
        277 => ("CONFIDENCE", 3),
        278 => ("CRITBINOM", 3),
        279 => ("EVEN", 1),
        280 => ("EXPONDIST", 3),
        281 => ("FDIST", 3),
        282 => ("FINV", 3),
        283 => ("FISHER", 1),
        284 => ("FISHERINV", 1),
        285 => ("FLOOR", 2),
        286 => ("GAMMADIST", 4),
        287 => ("GAMMAINV", 3),
        288 => ("CEILING", 2),
        289 => ("HYPGEOMDIST", 4),
        290 => ("LOGNORMDIST", 3),
        291 => ("LOGINV", 3),
        292 => ("NEGBINOMDIST", 3),
        293 => ("NORMDIST", 4),
        294 => ("NORMSDIST", 1),
        295 => ("NORMINV", 3),
        296 => ("NORMSINV", 1),
        297 => ("STANDARDIZE", 3),
        298 => ("ODD", 1),
        299 => ("PERMUT", 2),
        300 => ("POISSON", 3),
        301 => ("TDIST", 3),
        302 => ("WEIBULL", 4),
        303 => ("SUMXMY2", 2),
        304 => ("SUMX2MY2", 2),
        305 => ("SUMX2PY2", 2),
        306 => ("CHITEST", 2),
        307 => ("CORREL", 2),
        308 => ("COVAR", 2),
        309 => ("FORECAST", 3),
        310 => ("FTEST", 2),
        311 => ("INTERCEPT", 2),
        312 => ("PEARSON", 2),
        313 => ("RSQ", 2),
        314 => ("STEYX", 2),
        315 => ("SLOPE", 2),
        316 => ("TTEST", 4),
        317 => ("PROB", VAR),
        318 => ("DEVSQ", VAR),
        319 => ("GEOMEAN", VAR),
        320 => ("HARMEAN", VAR),
        321 => ("SUMSQ", VAR),
        322 => ("KURT", VAR),
        323 => ("SKEW", VAR),
        324 => ("ZTEST", VAR),
        325 => ("LARGE", 2),
        326 => ("SMALL", 2),
        327 => ("QUARTILE", 2),
        328 => ("PERCENTILE", 2),
        329 => ("PERCENTRANK", VAR),
        330 => ("MODE", VAR),
        331 => ("TRIMMEAN", 2),
        332 => ("TINV", 2),
        336 => ("CONCATENATE", VAR),
        337 => ("POWER", 2),
        342 => ("RADIANS", 1),
        343 => ("DEGREES", 1),
        344 => ("SUBTOTAL", VAR),
        345 => ("SUMIF", VAR),
        346 => ("COUNTIF", 2),
        347 => ("COUNTBLANK", 1),
        350 => ("ISPMT", 4),
        351 => ("DATEDIF", 3),
        352 => ("DATESTRING", 1),
        353 => ("NUMBERSTRING", 2),
        354 => ("ROMAN", VAR),
        358 => ("GETPIVOTDATA", VAR),
        359 => ("HYPERLINK", VAR),
        360 => ("PHONETIC", 1),
        361 => ("AVERAGEA", VAR),
        362 => ("MAXA", VAR),
        363 => ("MINA", VAR),
        364 => ("STDEVPA", VAR),
        365 => ("VARPA", VAR),
        366 => ("STDEVA", VAR),
        367 => ("VARA", VAR),
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_numbers_that_matter_most_are_the_ones_everybody_uses() {
        assert_eq!(lookup(4), Some(("SUM", VAR)));
        assert_eq!(lookup(1), Some(("IF", VAR)));
        assert_eq!(lookup(102), Some(("VLOOKUP", VAR)));
        assert_eq!(lookup(27), Some(("ROUND", 2)));
    }

    #[test]
    fn a_function_this_build_does_not_know_is_reported_rather_than_invented() {
        assert_eq!(lookup(9_999), None);
    }
}
