//! Charts, read out of a real workbook and written back into one.
//!
//! Against the corpus rather than a hand-written fixture, because the shape of
//! a chart part is exactly the thing a hand-written fixture gets wrong: three
//! parts, two relationship hops, and a namespace prefix on every element.

use std::io::Cursor;
use std::path::{Path, PathBuf};

use ss_model::ChartKind;
use ss_xlsx::XlsxDocument;

fn corpus_file() -> Option<PathBuf> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus/xlsx/charts.xlsx");
    path.exists().then_some(path)
}

#[test]
fn a_real_workbooks_charts_come_back_with_their_data() {
    let Some(path) = corpus_file() else {
        // The corpus is generated by `corpus/generate.ps1` through real Excel
        // and is not always present. Silence rather than a failure: the
        // fidelity harness is what reports an empty corpus.
        return;
    };
    let doc = XlsxDocument::open(&path).expect("opens");
    let charts: Vec<_> = doc.workbook.sheets.iter().flat_map(|s| &s.charts).collect();
    assert!(!charts.is_empty(), "the corpus file has charts in it");

    let kinds: Vec<&ChartKind> = charts.iter().map(|c| &c.kind).collect();
    assert!(kinds.contains(&&ChartKind::Bar), "{kinds:?}");
    assert!(kinds.contains(&&ChartKind::Line), "{kinds:?}");
    assert!(kinds.contains(&&ChartKind::Pie), "{kinds:?}");

    for chart in &charts {
        let series = chart.series.first().expect("a series");
        assert!(
            series.values_ref.is_some(),
            "the reference is what makes it redraw"
        );
        assert!(
            series.values.iter().any(Option::is_some),
            "and the cache is what makes it drawable without one"
        );
        assert!(!chart.categories().is_empty());
    }
}

#[test]
fn retitling_a_chart_survives_a_save_and_changes_nothing_else() {
    let Some(path) = corpus_file() else { return };
    let mut doc = XlsxDocument::open(&path).expect("opens");
    let before: Vec<String> = doc
        .package
        .parts()
        .map(|p| p.name.as_str().to_string())
        .collect();

    let target = doc.workbook.sheets[0].charts[0].part.clone();
    doc.workbook.sheets[0].charts[0].title = Some("Sales by month".to_string());

    let mut bytes = Vec::new();
    doc.write_to(Cursor::new(&mut bytes)).expect("writes");
    let reopened = XlsxDocument::read(Cursor::new(bytes)).expect("reads back");

    assert_eq!(
        reopened.workbook.sheets[0].charts[0].title.as_deref(),
        Some("Sales by month")
    );
    assert_eq!(
        reopened
            .package
            .parts()
            .map(|p| p.name.as_str().to_string())
            .collect::<Vec<_>>()
            .len(),
        before.len(),
        "no part was added or lost"
    );

    // Every part except the one chart is byte for byte what it was. The chart
    // parts of the *other* charts included: a retitle must not touch them.
    for part in reopened.package.parts() {
        if part.name.as_str() == target {
            continue;
        }
        let original = doc.package.part(&part.name).expect("was there before");
        if part.name.as_str().contains("worksheets")
            || part.name.as_str().contains("sharedStrings")
            || part.name.as_str().contains("styles")
        {
            // Those three go through the edit on every save by design.
            continue;
        }
        assert_eq!(
            original.data(),
            part.data(),
            "{} changed",
            part.name.as_str()
        );
    }
}

#[test]
fn a_chart_nobody_retitled_is_not_rewritten() {
    let Some(path) = corpus_file() else { return };
    let mut doc = XlsxDocument::open(&path).expect("opens");
    let target = doc.workbook.sheets[0].charts[0].part.clone();
    let name = ooxml::PartName::new(&target).expect("valid");
    let original = doc.package.part(&name).expect("present").data().to_vec();

    let mut bytes = Vec::new();
    doc.write_to(Cursor::new(&mut bytes)).expect("writes");
    let reopened = XlsxDocument::read(Cursor::new(bytes)).expect("reads back");

    assert_eq!(
        reopened.package.part(&name).expect("still there").data(),
        original.as_slice(),
        "a save must not normalize a chart it was not asked to change"
    );
}
