//! Charts, read out of a real workbook and written back into one.
//!
//! Against the corpus rather than a hand-written fixture, because the shape of
//! a chart part is exactly the thing a hand-written fixture gets wrong: three
//! parts, two relationship hops, and a namespace prefix on every element.

use std::io::Cursor;
use std::path::{Path, PathBuf};

use ss_model::ChartKind;
use ss_xlsx::XlsxDocument;

fn corpus_file() -> Option<PathBuf> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus/xlsx/charts.xlsx");
    path.exists().then_some(path)
}

#[test]
fn a_real_workbooks_charts_come_back_with_their_data() {
    let Some(path) = corpus_file() else {
        // The corpus is generated by `corpus/generate.ps1` through real Excel
        // and is not always present. Silence rather than a failure: the
        // fidelity harness is what reports an empty corpus.
        return;
    };
    let doc = XlsxDocument::open(&path).expect("opens");
    let charts: Vec<_> = doc.workbook.sheets.iter().flat_map(|s| &s.charts).collect();
    assert!(!charts.is_empty(), "the corpus file has charts in it");

    let kinds: Vec<&ChartKind> = charts.iter().map(|c| &c.plot.kind).collect();
    assert!(kinds.contains(&&ChartKind::Bar), "{kinds:?}");
    assert!(kinds.contains(&&ChartKind::Line), "{kinds:?}");
    assert!(kinds.contains(&&ChartKind::Pie), "{kinds:?}");

    for chart in &charts {
        let series = chart.plot.series.first().expect("a series");
        assert!(
            series.values_ref.is_some(),
            "the reference is what makes it redraw"
        );
        assert!(
            series.values.iter().any(Option::is_some),
            "and the cache is what makes it drawable without one"
        );
        assert!(!chart.plot.categories().is_empty());
    }
}

#[test]
fn retitling_a_chart_survives_a_save_and_changes_nothing_else() {
    let Some(path) = corpus_file() else { return };
    let mut doc = XlsxDocument::open(&path).expect("opens");
    let before: Vec<String> = doc
        .package
        .parts()
        .map(|p| p.name.as_str().to_string())
        .collect();

    let target = doc.workbook.sheets[0].charts[0].part.clone();
    doc.workbook.sheets[0].charts[0].plot.title = Some("Sales by month".to_string());

    let mut bytes = Vec::new();
    doc.write_to(Cursor::new(&mut bytes)).expect("writes");
    let reopened = XlsxDocument::read(Cursor::new(bytes)).expect("reads back");

    assert_eq!(
        reopened.workbook.sheets[0].charts[0].plot.title.as_deref(),
        Some("Sales by month")
    );
    assert_eq!(
        reopened
            .package
            .parts()
            .map(|p| p.name.as_str().to_string())
            .collect::<Vec<_>>()
            .len(),
        before.len(),
        "no part was added or lost"
    );

    // Every part except the one chart is byte for byte what it was. The chart
    // parts of the *other* charts included: a retitle must not touch them.
    for part in reopened.package.parts() {
        if part.name.as_str() == target {
            continue;
        }
        let original = doc.package.part(&part.name).expect("was there before");
        if part.name.as_str().contains("worksheets")
            || part.name.as_str().contains("sharedStrings")
            || part.name.as_str().contains("styles")
        {
            // Those three go through the edit on every save by design.
            continue;
        }
        assert_eq!(
            original.data(),
            part.data(),
            "{} changed",
            part.name.as_str()
        );
    }
}

#[test]
fn a_chart_nobody_retitled_is_not_rewritten() {
    let Some(path) = corpus_file() else { return };
    let mut doc = XlsxDocument::open(&path).expect("opens");
    let target = doc.workbook.sheets[0].charts[0].part.clone();
    let name = ooxml::PartName::new(&target).expect("valid");
    let original = doc.package.part(&name).expect("present").data().to_vec();

    let mut bytes = Vec::new();
    doc.write_to(Cursor::new(&mut bytes)).expect("writes");
    let reopened = XlsxDocument::read(Cursor::new(bytes)).expect("reads back");

    assert_eq!(
        reopened.package.part(&name).expect("still there").data(),
        original.as_slice(),
        "a save must not normalize a chart it was not asked to change"
    );
}

#[test]
fn a_moved_chart_keeps_its_new_anchor_across_a_save() {
    let Some(path) = corpus_file() else { return };
    let mut doc = XlsxDocument::open(&path).expect("opens");
    let sheet_idx = doc
        .workbook
        .sheets
        .iter()
        .position(|s| !s.charts.is_empty())
        .expect("a chart somewhere");

    let moved = match doc.workbook.sheets[sheet_idx].charts[0].anchor.clone() {
        ss_model::Anchor::TwoCell { mut from, mut to } => {
            from.row += 5;
            to.row += 5;
            ss_model::Anchor::TwoCell { from, to }
        }
        other => other,
    };
    doc.workbook.sheets[sheet_idx].charts[0].anchor = moved.clone();

    let parts_before = doc.package.parts().count();
    let mut bytes = Vec::new();
    doc.write_to(Cursor::new(&mut bytes)).expect("writes");
    let reopened = XlsxDocument::read(Cursor::new(bytes)).expect("reads back");

    assert_eq!(
        reopened.workbook.sheets[sheet_idx].charts[0].anchor, moved,
        "the anchor the user dragged to is the anchor the file keeps"
    );
    assert_eq!(
        reopened.package.parts().count(),
        parts_before,
        "no part was added or lost"
    );
}

#[test]
fn a_deleted_chart_stays_gone_and_every_part_stays_put() {
    let Some(path) = corpus_file() else { return };
    let mut doc = XlsxDocument::open(&path).expect("opens");
    let sheet_idx = doc
        .workbook
        .sheets
        .iter()
        .position(|s| !s.charts.is_empty())
        .expect("a chart somewhere");
    let count = doc.workbook.sheets[sheet_idx].charts.len();
    let kept: Vec<_> = doc.workbook.sheets[sheet_idx]
        .charts
        .iter()
        .skip(1)
        .map(|c| c.anchor.clone())
        .collect();
    doc.workbook.sheets[sheet_idx].charts.remove(0);

    let parts_before = doc.package.parts().count();
    let mut bytes = Vec::new();
    doc.write_to(Cursor::new(&mut bytes)).expect("writes");
    let reopened = XlsxDocument::read(Cursor::new(bytes)).expect("reads back");

    assert_eq!(
        reopened.workbook.sheets[sheet_idx].charts.len(),
        count - 1,
        "the chart is gone from the drawing"
    );
    assert_eq!(
        reopened.workbook.sheets[sheet_idx]
            .charts
            .iter()
            .map(|c| c.anchor.clone())
            .collect::<Vec<_>>(),
        kept,
        "its neighbours kept their anchors"
    );
    // The chart part itself stays in the package, orphaned rather than
    // dangling — the same policy pictures follow, because a missing part a
    // relationship still names is a file Excel refuses to open.
    assert_eq!(reopened.package.parts().count(), parts_before);
}

#[test]
fn a_real_workbooks_pivot_table_is_found_with_its_fields() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus/xlsx/pivot-table.xlsx");
    if !path.exists() {
        return;
    }
    let doc = XlsxDocument::open(&path).expect("opens");
    let pivots: Vec<_> = doc.workbook.sheets.iter().flat_map(|s| &s.pivots).collect();
    assert!(
        !pivots.is_empty(),
        "the corpus file has a pivot table in it"
    );

    let pivot = pivots[0];
    assert!(pivot.location.rows() > 1 && pivot.location.cols() >= 1);
    assert!(
        !pivot.fields.is_empty(),
        "the fields are named from the cache, not from the layout"
    );
    // The whole reason the region is read: an editor has to leave it alone.
    let inside = pivot.location.start;
    assert!(doc
        .workbook
        .sheets
        .iter()
        .any(|s| s.pivot_at(inside).is_some()));
}

/// A chart the application made, saved into a workbook that never had one.
///
/// The end-to-end question, and the only one that matters for inserting: not
/// "did we write plausible XML" but "does a reader find a chart where we put
/// one" — three parts, two relationship hops, and a content type, any of which
/// being wrong means Excel reports the file as damaged.
#[test]
fn a_chart_inserted_into_a_blank_workbook_comes_back_as_a_chart() {
    use ss_model::chart::{Anchor, AnchorPoint, LegendPosition, Series};
    use ss_model::{Chart, StyleId, Workbook};

    let mut book = Workbook::blank();
    for (row, (month, sales)) in [("Jan", 10.0), ("Feb", 12.5), ("Mar", 9.0)]
        .into_iter()
        .enumerate()
    {
        let row = row as u32 + 1;
        let cell = ss_formula::edit::typed_cell(&mut book, 0, StyleId::DEFAULT, month);
        book.sheets[0].set(ss_model::CellRef::new(row, 0), cell);
        let cell = ss_formula::edit::typed_cell(&mut book, 0, StyleId::DEFAULT, &sales.to_string());
        book.sheets[0].set(ss_model::CellRef::new(row, 1), cell);
    }
    let corner = |col, row| AnchorPoint {
        col,
        row,
        ..Default::default()
    };
    book.sheets[0].charts.push(Chart {
        part: String::new(),
        drawing_part: String::new(),
        anchor_index: 0,
        anchor: Anchor::TwoCell {
            from: corner(3, 1),
            to: corner(9, 16),
        },
        plot: ss_model::chart::Plot {
            kind: ChartKind::Bar,
            grouping: ss_model::chart::Grouping::Clustered,
            horizontal: false,
            title: Some("Sales".to_string()),
            title_ref: None,
            legend: Some(LegendPosition::Right),
            series: vec![Series {
                name: Some("Sales".to_string()),
                name_ref: Some("Sheet1!$B$1".to_string()),
                values_ref: Some("Sheet1!$B$2:$B$4".to_string()),
                values: vec![Some(10.0), Some(12.5), Some(9.0)],
                categories_ref: Some("Sheet1!$A$2:$A$4".to_string()),
                categories: vec!["Jan".into(), "Feb".into(), "Mar".into()],
                color: None,
                ..Series::default()
            }],
            ..ss_model::chart::Plot::default()
        },
    });

    let mut doc = XlsxDocument::new(book).expect("authors a package");
    let mut buffer = Cursor::new(Vec::new());
    doc.write_to(&mut buffer).expect("writes");

    let reopened = XlsxDocument::read(Cursor::new(buffer.into_inner())).expect("reads back");
    let charts = &reopened.workbook.sheets[0].charts;
    assert_eq!(
        charts.len(),
        1,
        "one chart, found by a reader that is not us"
    );
    let chart = &charts[0];
    assert_eq!(chart.plot.kind, ChartKind::Bar);
    assert_eq!(chart.plot.title.as_deref(), Some("Sales"));
    assert_eq!(chart.plot.legend, Some(LegendPosition::Right));
    assert_eq!(chart.plot.series.len(), 1);
    assert_eq!(
        chart.plot.series[0].values,
        [Some(10.0), Some(12.5), Some(9.0)]
    );
    assert_eq!(chart.plot.series[0].categories, ["Jan", "Feb", "Mar"]);
    assert_eq!(
        chart.anchor,
        Anchor::TwoCell {
            from: corner(3, 1),
            to: corner(9, 16)
        },
        "and it is where it was put"
    );
    assert!(
        !chart.part.is_empty() && !chart.drawing_part.is_empty(),
        "the model now names the parts it lives in"
    );
}
